// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import "../NuxAgentNFTBase.sol";

/**
 * @title MarketingAgentNFT
 * @notice AI Agent NFTs specialized for Marketing & Growth Automation
 * @dev Category: MARKETING
 *
 * CAPABILITIES:
 *   - NFT campaign creation and management with on-chain budget tracking
 *   - Conversion tracking integrated with ReferralSystem.sol
 *   - A/B testing framework for on-chain campaign parameters
 *   - AI copywriting for NFT descriptions, listings, social posts
 *   - Market analysis (floor price trends, volume, demand forecasting)
 *   - Referral bonus multiplier boost for agent owners
 *
 * REFERRAL INTEGRATION:
 *   Marketing agents can boost the referral discount percentage for their owner
 *   by up to 2x (from 10% base to 20% max) based on agent level/reputation.
 *   This integrates with the existing ReferralSystem.sol.
 *
 * GEMINI INTEGRATION:
 *   - Model: gemini-2.0-flash (fast for campaign generation)
 *   - Temperature: 0.8 (creative for copy, persuasive writing)
 *   - Tools: web grounding (current market trends), code execution (analytics)
 *   - System prompt: Growth hacker + NFT market specialist
 *
 * MINI-GAME TASKS:
 *   - TASK_LAUNCH_CAMPAIGN: Design and "publish" a marketing campaign
 *   - TASK_ANALYZE_MARKET: Generate NFT market analysis report
 *   - TASK_WRITE_COPY: Create 5 NFT listing descriptions rated >80/100 by community
 *   - TASK_OPTIMIZE_REFERRAL: Improve referral conversion rate by >5%
 */
contract MarketingAgentNFT is NuxAgentNFTBase {

    // ============================================
    // ERRORS
    // ============================================
    error WrongCategory();
    error TokenNotFound();
    error NotAuthorized();
    error InvalidDuration();
    error MaxCampaignsReached();
    error InvalidCampaign();

    // ============================================
    // MARKETING-SPECIFIC STORAGE
    // ============================================

    struct MarketingProfile {
        uint256 campaignsLaunched;    // Total marketing campaigns executed
        uint256 totalBudgetSpent;     // Total POL spent across campaigns
        uint256 conversionsTracked;   // Total conversions attributed
        uint256 revenueGenerated;     // Estimated revenue generated by campaigns
        uint256 referralMultiplier;   // Boost to owner's referral discount (100 = 1x, 200 = 2x)
        uint256 copyPiecesCreated;    // AI-generated copy pieces
    }

    struct Campaign {
        string  name;
        string  targetAudience;
        uint256 budget;              // In wei (POL)
        uint256 spent;               // Actual spend
        uint256 startTime;
        uint256 endTime;
        uint256 conversions;
        bool    active;
    }

    mapping(uint256 => MarketingProfile)   public marketingProfiles;
    mapping(uint256 => Campaign[])         public campaigns;

    // Max referral multiplier: 200 (2x over base)
    uint256 public constant MAX_REFERRAL_MULTIPLIER = 200;

    // ============================================
    // EVENTS
    // ============================================
    event CampaignLaunched(uint256 indexed tokenId, uint256 campaignIndex, string name, uint256 budget);
    event ConversionRecorded(uint256 indexed tokenId, uint256 campaignIndex, address referredUser);
    event ReferralMultiplierUpdated(uint256 indexed tokenId, uint256 newMultiplier);
    event CopyCreated(uint256 indexed tokenId, string contentType, uint256 totalPieces);
    event MarketAnalysisGenerated(uint256 indexed tokenId, string reportURI);

    /// @custom:oz-upgrades-unsafe-allow constructor
    constructor() {
        _disableInitializers();
    }

    function initialize(
        address admin_,
        address treasuryManager_,
        address levelingSystem_,
        address erc6551Impl_,
        uint256 mintingFee_
    ) public initializer {
        __NuxAgentNFTBase_init(
            "NuxChain Marketing Agent",
            "NXMKT",
            admin_,
            treasuryManager_,
            levelingSystem_,
            erc6551Impl_,
            mintingFee_,
            500
        );
    }

    // ============================================
    // FACTORY ENTRY POINT
    // ============================================

    function mintFromFactory(
        address recipient,
        AgentConfig memory config,
        string memory tokenURI_
    ) external payable onlyRole(FACTORY_ROLE) returns (uint256 tokenId) {
        if (config.category != AgentCategory.MARKETING) revert WrongCategory();
        _collectMintingFee();
        tokenId = _mintAgent(recipient, config, tokenURI_);
        marketingProfiles[tokenId] = MarketingProfile({
            campaignsLaunched:    0,
            totalBudgetSpent:     0,
            conversionsTracked:   0,
            revenueGenerated:     0,
            referralMultiplier:   100, // Start at 1x
            copyPiecesCreated:    0
        });
    }

    function mint(
        address recipient,
        AgentConfig memory config,
        string memory tokenURI_
    ) external payable onlyRole(ADMIN_ROLE) nonReentrant returns (uint256 tokenId) {
        if (config.category != AgentCategory.MARKETING) revert WrongCategory();
        _collectMintingFee();
        tokenId = _mintAgent(recipient, config, tokenURI_);
        marketingProfiles[tokenId] = MarketingProfile({
            campaignsLaunched:  0,
            totalBudgetSpent:   0,
            conversionsTracked: 0,
            revenueGenerated:   0,
            referralMultiplier: 100,
            copyPiecesCreated:  0
        });
    }

    // ============================================
    // CAMPAIGN MANAGEMENT
    // ============================================

    /**
     * @notice Launch a marketing campaign on-chain
     * @dev Campaign budget is tracked — agent's TBA can pay campaign costs via Paymaster
     */
    function launchCampaign(
        uint256 tokenId,
        string calldata name,
        string calldata targetAudience,
        uint256 budget,
        uint256 durationDays
    ) external {
        if (!_exists(tokenId)) revert TokenNotFound();
        if (ownerOf(tokenId) != msg.sender &&
            !(currentRenter[tokenId] == msg.sender && block.timestamp < rentalExpiry[tokenId]))
            revert NotAuthorized();
        if (durationDays == 0 || durationDays > 365) revert InvalidDuration();
        if (campaigns[tokenId].length >= 50) revert MaxCampaignsReached();

        campaigns[tokenId].push(Campaign({
            name:           name,
            targetAudience: targetAudience,
            budget:         budget,
            spent:          0,
            startTime:      block.timestamp,
            endTime:        block.timestamp + (durationDays * 1 days),
            conversions:    0,
            active:         true
        }));

        marketingProfiles[tokenId].campaignsLaunched++;
        uint256 campaignIdx = campaigns[tokenId].length - 1;

        _awardXP(ownerOf(tokenId), 20);
        emit CampaignLaunched(tokenId, campaignIdx, name, budget);
    }

    // ============================================
    // TASK RECORDING
    // ============================================

    function recordConversion(
        uint256 tokenId,
        uint256 campaignIndex,
        address referredUser,
        uint256 xpEarned
    ) external onlyRole(REGISTRY_ROLE) {
        if (!_exists(tokenId)) revert TokenNotFound();
        if (campaignIndex >= campaigns[tokenId].length) revert InvalidCampaign();

        campaigns[tokenId][campaignIndex].conversions++;
        marketingProfiles[tokenId].conversionsTracked++;

        _awardXP(ownerOf(tokenId), xpEarned);
        emit ConversionRecorded(tokenId, campaignIndex, referredUser);
    }

    function recordCopyCreated(
        uint256 tokenId,
        string calldata contentType,
        uint256 xpEarned
    ) external onlyRole(REGISTRY_ROLE) {
        if (!_exists(tokenId)) revert TokenNotFound();
        marketingProfiles[tokenId].copyPiecesCreated++;
        _awardXP(ownerOf(tokenId), xpEarned);
        emit CopyCreated(tokenId, contentType, marketingProfiles[tokenId].copyPiecesCreated);
    }

    function recordMarketAnalysis(
        uint256 tokenId,
        string calldata reportURI,
        uint256 xpEarned
    ) external onlyRole(REGISTRY_ROLE) {
        if (!_exists(tokenId)) revert TokenNotFound();
        _awardXP(ownerOf(tokenId), xpEarned);
        emit MarketAnalysisGenerated(tokenId, reportURI);
    }

    /**
     * @notice Update the referral multiplier based on agent performance (REGISTRY_ROLE)
     * @dev Multiplier is read by MarketingAgentNFT-aware frontend to boost discounts
     *      Capped at MAX_REFERRAL_MULTIPLIER (2x)
     */
    function updateReferralMultiplier(uint256 tokenId, uint256 newMultiplier) external onlyRole(REGISTRY_ROLE) {
        if (!_exists(tokenId)) revert TokenNotFound();
        if (newMultiplier > MAX_REFERRAL_MULTIPLIER) newMultiplier = MAX_REFERRAL_MULTIPLIER;
        marketingProfiles[tokenId].referralMultiplier = newMultiplier;
        emit ReferralMultiplierUpdated(tokenId, newMultiplier);
    }

    uint256[50] private __gap;

}
